#!/usr/bin/env bash
set -euo pipefail

# This init script prepares service on Onyxia.
# Purpose: {"chart_id":"rstudio","packages":["shiny","DBI","RPostgres","dplyr"],"files":{"app.R":"library(shiny)\nlibrary(DBI)\nlibrary(RPostgres)\n\n# Configuration de la connexion\n# Les variables d'environnement sont generees par le chart postgresql-cnpg\n# ou peuvent etre configurees manuellement.\n# Pour cet exemple, on suppose que le service postgresql est accessible\n# via le nom du service dans le meme namespace.\n\nui <- fluidPage(\n  titlePanel(\"Connexion Shiny - PostgreSQL\"),\n  sidebarLayout(\n    sidebarPanel(\n      textInput(\"host\", \"Host PostgreSQL\", \"postgresql-cnpg\"),\n      textInput(\"port\", \"Port\", \"5432\"),\n      textInput(\"dbname\", \"Base de donnees\", \"postgres\"),\n      textInput(\"user\", \"Utilisateur\", \"postgres\"),\n      textInput(\"password\", \"Mot de passe\", \"\"),\n      actionButton(\"connect\", \"Se connecter\")\n    ),\n    mainPanel(\n      verbatimTextOutput(\"status\"),\n      tableOutput(\"data\")\n    )\n  )\n)\n\nserver <- function(input, output, session) {\n  conn <- reactiveVal(NULL)\n  \n  observeEvent(input$connect, {\n    tryCatch({\n      c <- dbConnect(\n        Postgres(),\n        host = input$host,\n        port = as.integer(input$port),\n        dbname = input$dbname,\n        user = input$user,\n        password = input$password\n      )\n      conn(c)\n      showNotification(\"Connecte avec succes !\", type = \"message\")\n    }, error = function(e) {\n      showNotification(paste(\"Erreur de connexion :\", e$message), type = \"error\")\n    })\n  })\n  \n  output$status <- renderText({\n    if (is.null(conn())) {\n      \"Pas connecte\"\n    } else {\n      \"Connecte a : \", input$host\n    }\n  })\n  \n  output$data <- renderTable({\n    if (is.null(conn())) {\n      return(NULL)\n    }\n    # Exemple de requete simple\n    tryCatch({\n      dbGetQuery(conn(), \"SELECT 1 as test\")\n    }, error = function(e) {\n      data.frame(erreur = e$message)\n    })\n  })\n}\n\nshinyApp(ui = ui, server = server)","purpose":"Application Shiny connectee a PostgreSQL","start_command":"R -e \"shiny::runApp('app.R', port=8080, host='0.0.0.0')\""}
# Expected parameters : None

WORK_DIR="${WORK_DIR:-/home/onyxia/work}"
mkdir -p "${WORK_DIR}"
echo "No initialization action requested."
